# Generated by Django 2.2.3 on 2019-12-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllMoneyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneyType', models.CharField(max_length=3)),
                ('cashIN', models.TextField(default='0')),
                ('cashOUT', models.TextField(default='0')),
                ('spotIN', models.TextField(default='0')),
                ('spotOUT', models.TextField(default='0')),
                ('bank', models.CharField(max_length=6)),
                ('fee', models.TextField(default='無')),
                ('updateTime', models.TextField()),
            ],
            options={
                'db_table': 'AllMoneyInfo',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineBotID', models.TextField()),
                ('moneyType', models.CharField(max_length=3)),
                ('INorOUT', models.CharField(max_length=3)),
                ('bank', models.CharField(max_length=10)),
                ('lowerBound', models.TextField()),
            ],
            options={
                'db_table': 'UserInfo',
            },
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineBotID', models.TextField()),
                ('moneyORpass', models.TextField(default='現金/現鈔')),
                ('moneyType', models.CharField(default='JPY', max_length=3)),
                ('buyORsell', models.IntegerField(default='買入')),
                ('bank', models.CharField(default='臺灣銀行', max_length=10)),
            ],
            options={
                'db_table': 'UserStatus',
            },
        ),
    ]
