# Generated by Django 2.2.3 on 2019-12-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='buyORsell',
            field=models.TextField(default='買入'),
        ),
    ]
