# Generated by Django 2.2.3 on 2019-12-17 12:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20191214_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyorlife',
            name='Dest_uID',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_user', to='webapp.User'),
        ),
        migrations.AddField(
            model_name='moneyorlife',
            name='Src_uID',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s_user', to='webapp.User'),
        ),
        migrations.AlterField(
            model_name='personporj',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 17, 20, 59, 31, 789915)),
        ),
    ]
