# Generated by Django 2.2.3 on 2019-12-17 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20191217_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personporj',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 17, 21, 1, 57, 798657)),
        ),
    ]
