# Generated by Django 2.2.3 on 2019-12-19 09:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20191217_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 9, 11, 23, 503758, tzinfo=utc)),
        ),
    ]
