# Generated by Django 2.2.3 on 2019-12-19 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20191219_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 17, 19, 0, 342183)),
        ),
    ]
