# Generated by Django 2.2.3 on 2019-12-19 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20191219_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 17, 55, 21, 207786)),
        ),
        migrations.AlterModelTable(
            name='money',
            table='Money',
        ),
    ]
