# Generated by Django 2.2.3 on 2019-12-19 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20191219_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personporj',
            name='time',
        ),
        migrations.AddField(
            model_name='personporj',
            name='Time',
            field=models.CharField(default='2019-12-19-08-10-34', max_length=19),
        ),
        migrations.AlterField(
            model_name='groupinfo',
            name='uID',
            field=models.CharField(max_length=3, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='money',
            name='time',
            field=models.CharField(max_length=19),
        ),
        migrations.AlterField(
            model_name='user',
            name='Time',
            field=models.CharField(max_length=19),
        ),
        migrations.AlterField(
            model_name='user',
            name='uID',
            field=models.CharField(max_length=3, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterModelTable(
            name='money',
            table=None,
        ),
    ]
